package com.yxc.imapi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}
	
	public java.lang.String getMessage() {
		return getStr("message");
	}

	public M setSendDate(java.util.Date sendDate) {
		set("send_date", sendDate);
		return (M)this;
	}
	
	public java.util.Date getSendDate() {
		return get("send_date");
	}

	public M setChannel(java.lang.String channel) {
		set("channel", channel);
		return (M)this;
	}
	
	public java.lang.String getChannel() {
		return getStr("channel");
	}

	public M setSendUser(java.lang.String sendUser) {
		set("sendUser", sendUser);
		return (M)this;
	}
	
	public java.lang.String getSendUser() {
		return getStr("sendUser");
	}

	public M setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
		return (M)this;
	}
	
	public java.lang.String getReceiver() {
		return getStr("receiver");
	}

	public M setContentType(java.lang.Integer contentType) {
		set("contentType", contentType);
		return (M)this;
	}
	
	public java.lang.Integer getContentType() {
		return getInt("contentType");
	}

	public M setPictureUrl(java.lang.String pictureUrl) {
		set("pictureUrl", pictureUrl);
		return (M)this;
	}
	
	public java.lang.String getPictureUrl() {
		return getStr("pictureUrl");
	}

	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M)this;
	}
	
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M)this;
	}
	
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	public M setCoordinateType(java.lang.String coordinateType) {
		set("coordinateType", coordinateType);
		return (M)this;
	}
	
	public java.lang.String getCoordinateType() {
		return getStr("coordinateType");
	}

	public M setIsRead(java.lang.Integer isRead) {
		set("isRead", isRead);
		return (M)this;
	}
	
	public java.lang.Integer getIsRead() {
		return getInt("isRead");
	}

	public M setMsgType(java.lang.Integer msgType) {
		set("msgType", msgType);
		return (M)this;
	}
	
	public java.lang.Integer getMsgType() {
		return getInt("msgType");
	}

	public M setReadTime(java.util.Date readTime) {
		set("readTime", readTime);
		return (M)this;
	}
	
	public java.util.Date getReadTime() {
		return get("readTime");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setFileName(java.lang.String fileName) {
		set("fileName", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	public M setFileDownloadUrl(java.lang.String fileDownloadUrl) {
		set("fileDownloadUrl", fileDownloadUrl);
		return (M)this;
	}
	
	public java.lang.String getFileDownloadUrl() {
		return getStr("fileDownloadUrl");
	}

}
