package com.yxc.imapi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.String userId) {
		set("USER_ID", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("USER_ID");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("ROLE_ID", roleId);
		return (M)this;
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("ROLE_ID");
	}

	public M setSTATE(java.lang.Integer STATE) {
		set("STATE", STATE);
		return (M)this;
	}
	
	public java.lang.Integer getSTATE() {
		return getInt("STATE");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("CREATE_USER", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("CREATE_USER");
	}

}
