package com.yxc.imapi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserContacts<M extends BaseUserContacts<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setFriendId(java.lang.String friendId) {
		set("friend_id", friendId);
		return (M)this;
	}
	
	public java.lang.String getFriendId() {
		return getStr("friend_id");
	}

	public M setFriendLabel(java.lang.String friendLabel) {
		set("friend_label", friendLabel);
		return (M)this;
	}
	
	public java.lang.String getFriendLabel() {
		return getStr("friend_label");
	}

	public M setFriendNote(java.lang.String friendNote) {
		set("friend_note", friendNote);
		return (M)this;
	}
	
	public java.lang.String getFriendNote() {
		return getStr("friend_note");
	}

	public M setFriendStatus(java.lang.Integer friendStatus) {
		set("friend_status", friendStatus);
		return (M)this;
	}
	
	public java.lang.Integer getFriendStatus() {
		return getInt("friend_status");
	}

	public M setFriendAddDirection(java.lang.String friendAddDirection) {
		set("friend_add_direction", friendAddDirection);
		return (M)this;
	}
	
	public java.lang.String getFriendAddDirection() {
		return getStr("friend_add_direction");
	}

	public M setFriendMessage(java.lang.String friendMessage) {
		set("friend_message", friendMessage);
		return (M)this;
	}
	
	public java.lang.String getFriendMessage() {
		return getStr("friend_message");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

}
