package com.yxc.imapi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserLatestInfo<M extends BaseUserLatestInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setFriendId(java.lang.String friendId) {
		set("friend_id", friendId);
		return (M)this;
	}
	
	public java.lang.String getFriendId() {
		return getStr("friend_id");
	}

	public M setUnreadCount(java.lang.Integer unreadCount) {
		set("unreadCount", unreadCount);
		return (M)this;
	}
	
	public java.lang.Integer getUnreadCount() {
		return getInt("unreadCount");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}
	
	public java.lang.String getMessage() {
		return getStr("message");
	}

	public M setSendDate(java.util.Date sendDate) {
		set("send_date", sendDate);
		return (M)this;
	}
	
	public java.util.Date getSendDate() {
		return get("send_date");
	}

	public M setChannel(java.lang.String channel) {
		set("channel", channel);
		return (M)this;
	}
	
	public java.lang.String getChannel() {
		return getStr("channel");
	}

	public M setSendUser(java.lang.String sendUser) {
		set("sendUser", sendUser);
		return (M)this;
	}
	
	public java.lang.String getSendUser() {
		return getStr("sendUser");
	}

	public M setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
		return (M)this;
	}
	
	public java.lang.String getReceiver() {
		return getStr("receiver");
	}

	public M setContentType(java.lang.Integer contentType) {
		set("contentType", contentType);
		return (M)this;
	}
	
	public java.lang.Integer getContentType() {
		return getInt("contentType");
	}

	public M setPictureUrl(java.lang.String pictureUrl) {
		set("pictureUrl", pictureUrl);
		return (M)this;
	}
	
	public java.lang.String getPictureUrl() {
		return getStr("pictureUrl");
	}

	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M)this;
	}
	
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M)this;
	}
	
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	public M setCoordinateType(java.lang.String coordinateType) {
		set("coordinateType", coordinateType);
		return (M)this;
	}
	
	public java.lang.String getCoordinateType() {
		return getStr("coordinateType");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("lastUpdateTime", lastUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getLastUpdateTime() {
		return get("lastUpdateTime");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

}
