server:
  port: 8088
  servlet:
    context-path: /api-im

config:
  jwt:
    # 加密密钥
    secret: sdjhakdhajdklsl;o653632
    # token有效时长
    expire: 28800
    redisexp: 7200
    # header 名称
    header: token

spring:
  redis:
    host: 124.222.4.40
    port: 6379
    database: 1
    password: chaodev666888
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.4.40:3306/im?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: yxc123456

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
