server:
  port: 8088
  servlet:
    context-path: /api-im

myserver:
  name: im-server

spring:
  redis:
    host: 152.136.134.234
    port: 6379
    database: 1
    password: yxcredis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: 666888

  qcloud:
    #API密钥secretId
    secretId: AKIDz5vUmoZ3FBqELBk22lEUTBclfIdhU0FD
    #API密钥secretKey
    secretKey: i9JDqCH4h7G8k7D2btueDpHUSAajbDYc
    #存储桶所属地域
    region: ap-chengdu
    #存储桶空间名称
    bucketName: yxccos-1253584179
#    bucketName: yxccos2-1253584179
    #存储桶访问域名
    url: https://yxccos-1253584179.cos.ap-chengdu.myqcloud.com
#    url: https://yxccos2-1253584179.cos.ap-chengdu.myqcloud.com
    #上传文件前缀路径(eg:/images/)
    prefix: /

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
