package com.yxc.imapi.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("avatar_history", "id", AvatarHistory.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("user_chat_session", "id", UserChatSession.class);
		arp.addMapping("user_contacts", "id", UserContacts.class);
		arp.addMapping("users", "id", Users.class);
	}
}

