package com.yxc.imapi.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("role", "role_id", Role.class);
		arp.addMapping("user_contacts", "id", UserContacts.class);
		arp.addMapping("user_latest_info", "id", UserLatestInfo.class);
		arp.addMapping("users", "id", Users.class);
	}
}

