package com.yxc.imapi.model;

import com.yxc.imapi.model.base.BaseAvatarHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AvatarHistory extends BaseAvatarHistory<AvatarHistory> {
	public static final AvatarHistory dao = new AvatarHistory().dao();
}
