package com.yxc.imapi.model;

import com.yxc.imapi.model.base.BaseUserContacts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserContacts extends BaseUserContacts<UserContacts> {
	public static final UserContacts dao = new UserContacts().dao();
}
