package com.yxc.imapi.model;

import com.yxc.imapi.model.base.BaseUserChatSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserChatSession extends BaseUserChatSession<UserChatSession> {
	public static final UserChatSession dao = new UserChatSession().dao();
}
