package com.yxc.imapi.model;

import com.yxc.imapi.model.base.BaseUserLatestInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLatestInfo extends BaseUserLatestInfo<UserLatestInfo> {
	public static final UserLatestInfo dao = new UserLatestInfo().dao();
}
